#!/bin/sh
#
# jpgMv file ... - rename jpeg files, name based on original date/time
#
# Mon Jan 12 13:03:36 GMT 2015
#
# Copyright (C) 2018 Peter Scott - p.scott@shu.ac.uk
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


# usage - display usage message
#
usage () {
  echo "Usage: $NAME [ -t ] file ..." >&2
  exit 1
}


# checkSimple file - check file is plain, readable, not empty
#
checkSimple () {
  file=$1
  ls "$file" > /dev/null 2>&1
  if [ $? -ne 0 ]
  then echo "$NAME: $file: does not exist" >&2
       return 1
  elif [ -d "$file" ]
  then echo "$NAME: $file: is a directory" >&2
       return 1
  elif [ ! -r "$file" ]
  then echo "$NAME: $file: is not readable" >&2
       return 1
  elif [ ! -s "$file" ]
  then echo "$NAME: $file: is empty" >&2
       return 1
  else
       return 0
  fi
}


# nextFreeNo dir date ext - get next free underscore number
#
nextFreeNo(){
  dir=$1; date=$2; ext=$3
  test -f "$dir/$date.$ext" || return
  ( cd "$dir"
    { ls ${date}_*."$ext" 2> /dev/null |
        sed 's/\.'"$ext"'//
             s/.*_//' |
          sort -n
      echo 999
    } |
    nl -n rz -s ' ' -w 2 -v 0 |
      sed -n '/^\([0-9][0-9]*\) \1$/d
              /./{ s/ .*//
                   p
                   q
              }'
  )
}


# doit file - do it to one file
#
doit () {
  source=$1
  file=`basename "$source"`
  dir=`dirname "$source"`
  ext=`echo "$file" | sed 's/.*\.//'`
  date=`jpgDate $timeNeeded "$source"`
  if [ -z $date ]
  then echo "$NAME: $source: no date/time" >&2
  else count=`nextFreeNo "$dir" "$date" "$ext"`
        case $count in
          '')
             : ;;
          [0-9][0-9])
             count=_$count
             ;;
          *)
             echo "$NAME: $source: would overflow ${date}_99" >&2
             exit 3
        esac
       if [ -f "$dir/$date$count.$ext" ]
       then echo "$NAME: $source: $dir/$date$count.$ext already exists" >&2
            exit 4   # should never happen
       fi
       mv "$source" "$dir/${date}$count.$ext"
  fi
}


# prevent the user giving the script a name with white space in it
# -- saving the hassle of quoting internal file names
#
NAME=`basename "$0"`
words=`echo "$NAME" | wc -w`
if [ $words -ne 1 ]
then echo "\`$NAME': I don't allow white space in command names" >&2
     exit 5
fi

while getopts ':t' option
do   case $option in
       t) timeNeeded='-t' ;;
      \?) echo "$NAME: bad option -- $OPTARG" >&2
          usage
     esac
done
shift `expr $OPTIND - 1`
test "$1" || usage
for file
do   checkSimple "$file" && doit "$file"
done
